import pytest
from fastapi.testclient import TestClient
from unittest.mock import patch
from app.main import app

client = TestClient(app)


@pytest.fixture
def default_text_response():
    """Fixture to mock the default text response."""
    return client.get("/text")


@pytest.fixture
def ollama_text_response():
    """Fixture to mock the response when Ollama is enabled."""
    with patch("utils.ollama.generate_document_with_ollama") as mock_ollama:
        mock_ollama.return_value = "This is a sample document generated by Ollama."
        yield client.get("/text")


@pytest.fixture
def fallback_text_response():
    """Fixture to mock the fallback text response when Ollama is disabled."""
    with patch("config.config.OLLAMA_ENABLED", False):
        return client.get("/text")


def test_return_text_success(default_text_response):
    """Test successful document generation with random content."""
    response = default_text_response
    assert response.status_code == 200
    assert response.headers["Content-Type"].startswith("text/plain")
    assert "Content-Disposition" in response.headers
    assert response.headers["Content-Disposition"].startswith("inline; filename=")
    assert response.headers["Content-Disposition"].endswith(".txt")
    assert len(response.content) > 0


@patch("config.config.OLLAMA_ENABLED", True)
@patch("utils.ollama.generate_document_with_ollama", return_value="This is a sample document generated by Ollama.")
def test_return_text_with_ollama(mock_generate_document_with_ollama):
    """Test document generation with Ollama enabled."""
    response = client.get("/text")

    # Ensure the mock was called
    mock_generate_document_with_ollama.assert_called_once()

    # Validate response
    assert response.status_code == 200
    assert response.headers["Content-Type"] == "text/plain; charset=utf-8"
    assert response.headers["Content-Disposition"].endswith(".txt")
    assert "This is a sample document generated by Ollama." in response.content.decode("utf-8")


def test_return_text_fallback(fallback_text_response):
    """Test document generation when Ollama is disabled or fails."""
    response = fallback_text_response
    assert response.status_code == 200
    assert response.headers["Content-Type"].startswith("text/html")
    assert "Content-Disposition" in response.headers
    assert response.headers["Content-Disposition"] == "inline; filename=document.html"
    assert "<h1>" in response.content.decode("utf-8")
    assert "<h2>" in response.content.decode("utf-8")
    assert "<p>" in response.content.decode("utf-8")


def test_return_text_with_filename(default_text_response):
    """Test document generation with a filename specified."""
    response = client.get("/text/samplefile.txt")
    assert response.status_code == 200
    assert response.headers["Content-Type"].startswith("text/plain")
    assert "Content-Disposition" in response.headers
    assert response.headers["Content-Disposition"] == "inline; filename=samplefile.txt"


def test_return_text_invalid_path():
    """Test invalid path handling for text document generation."""
    response = client.get("/text/invalidpath/extra")
    assert response.status_code == 404  # Should trigger a 404 error for invalid paths


def test_text_document_structure(default_text_response):
    """Test the structure of the generated text document content."""
    response = default_text_response
    assert response.status_code == 200
    content = response.content.decode("utf-8")

    # Check for general HTML structure
    assert "<h1>" in content  # Ensure heading is included
    assert "<h2>" in content  # Ensure subheadings are included
    assert "<p>" in content  # Ensure paragraphs are included
    assert "</h1>" in content  # Ensure closing tag for heading
    assert "</h2>" in content  # Ensure closing tag for subheading
    assert "</p>" in content  # Ensure closing tag for paragraphs
