import pytest
from fastapi.testclient import TestClient
from app import main
from unittest.mock import patch
import random

client = TestClient(main)

# Mock data for testing
mock_binary_data = b"Random binary data"
mock_file_name = "test_file.bin"


@pytest.fixture
def mock_generate_random_name():
    with patch("utils.helper.generate_random_name") as mock:
        yield mock


@pytest.fixture
def mock_faker_binary():
    with patch.object(random, "randint") as mock_randint:
        yield mock_randint


@pytest.fixture
def mock_fake_binary():
    with patch("faker.Faker.binary") as mock:
        yield mock


def test_return_binary_without_file_name(mock_generate_random_name, mock_fake_binary):
    # Mock the function to generate a random file name
    mock_generate_random_name.return_value = mock_file_name

    # Mock the random binary data generated by Faker
    mock_fake_binary.return_value = mock_binary_data

    # Test GET request without file_name
    response = client.get("/binary")
    assert response.status_code == 200
    assert response.content == mock_binary_data
    assert (
        response.headers["Content-Disposition"]
        == f"attachment; filename={mock_file_name}"
    )
    mock_generate_random_name.assert_called_once_with(".bin")


def test_return_binary_with_file_name(mock_fake_binary):
    # Mock the random binary data generated by Faker
    mock_fake_binary.return_value = mock_binary_data

    # Test GET request with file_name
    response = client.get(f"/binary/{mock_file_name}")
    assert response.status_code == 200
    assert response.content == mock_binary_data
    assert (
        response.headers["Content-Disposition"]
        == f"attachment; filename={mock_file_name}"
    )


def test_post_return_binary_without_file_name(
    mock_generate_random_name, mock_fake_binary
):
    # Mock the function to generate a random file name
    mock_generate_random_name.return_value = mock_file_name

    # Mock the random binary data generated by Faker
    mock_fake_binary.return_value = mock_binary_data

    # Test POST request without file_name
    response = client.post("/binary")
    assert response.status_code == 200
    assert response.content == mock_binary_data
    assert (
        response.headers["Content-Disposition"]
        == f"attachment; filename={mock_file_name}"
    )
    mock_generate_random_name.assert_called_once_with(".bin")


def test_post_return_binary_with_file_name(mock_fake_binary):
    # Mock the random binary data generated by Faker
    mock_fake_binary.return_value = mock_binary_data

    # Test POST request with file_name
    response = client.post(f"/binary/{mock_file_name}")
    assert response.status_code == 200
    assert response.content == mock_binary_data
    assert (
        response.headers["Content-Disposition"]
        == f"attachment; filename={mock_file_name}"
    )
